#!/usr/bin/env bash
# Azure cloud-init: installs GitLab Omnibus and configures Azure Blob object storage.
#
# Object storage uses a SAS token generated by Terraform at apply time.
# The token is written to /etc/gitlab/gitlab.rb (root-readable only) and
# never stored in source control or Terraform plan output.
#
# To rotate the SAS token: re-run terraform apply, then:
#   sudo gitlab-ctl reconfigure
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl ca-certificates

curl -fsSL https://packages.gitlab.com/install/repositories/gitlab/gitlab-${gitlab_edition}/script.deb.sh | bash
EXTERNAL_URL="https://${gitlab_domain}" apt-get install -y gitlab-${gitlab_edition}

# Restrict gitlab.rb permissions before writing credentials
chmod 0600 /etc/gitlab/gitlab.rb

cat >> /etc/gitlab/gitlab.rb << RUBYEOF
# Object storage — Azure Blob via SAS token
# SAS token is injected at provision time by Terraform; rotate by re-applying.
gitlab_rails['object_store']['enabled'] = true
gitlab_rails['object_store']['provider'] = 'AzureRM'
gitlab_rails['object_store']['connection'] = {
  'provider'                   => 'AzureRM',
  'azure_storage_account_name' => '${storage_account_name}',
  'azure_storage_access_key'   => '${storage_sas_token}'
}
gitlab_rails['object_store']['objects']['artifacts']['bucket'] = '${storage_container}'
gitlab_rails['object_store']['objects']['lfs']['bucket']       = '${storage_container}'
gitlab_rails['object_store']['objects']['uploads']['bucket']   = '${storage_container}'
gitlab_rails['object_store']['objects']['packages']['bucket']  = '${storage_container}'
RUBYEOF

gitlab-ctl reconfigure
